---
language: go
go:
- 1.x
before_install:
- node -v
- npm -v
install:
- npm install
- go get -t ./...
- go get -u gopkg.in/alecthomas/gometalinter.v2
- ln -s $GOPATH/bin/gometalinter.v2 $GOPATH/bin/gometalinter
- gometalinter --install
script:
- npm run commitlint-travis
- bash script/fmt.sh
- gometalinter ./...
- bash script/codecov-test.sh
after_success:
- go get github.com/mitchellh/gox
- go get -u github.com/tcnksm/ghr
- bash script/travis_build.sh
- bash script/codecov.sh
- bash script/travis_upload.sh
