package test

// Don't edit this file.
// This file is generated by gomic 0.5.2.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	test "github.com/suzuki-shunsuke/go-gencfg/internal/domain"
	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// CfgReaderMock is a mock.
	CfgReaderMock struct {
		t                      *testing.T
		name                   string
		callbackNotImplemented gomic.CallbackNotImplemented
		impl                   struct {
			Read func(src string) (test.Cfg, error)
		}
	}
)

// NewCfgReaderMock returns CfgReaderMock .
func NewCfgReaderMock(t *testing.T, cb gomic.CallbackNotImplemented) *CfgReaderMock {
	return &CfgReaderMock{
		t: t, name: "CfgReaderMock", callbackNotImplemented: cb}
}

// Read is a mock method.
func (mock CfgReaderMock) Read(src string) (test.Cfg, error) {
	methodName := "Read" // nolint: goconst
	if mock.impl.Read != nil {
		return mock.impl.Read(src)
	}
	if mock.callbackNotImplemented != nil {
		mock.callbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroRead(src)
}

// SetFuncRead sets a method and returns the mock.
func (mock *CfgReaderMock) SetFuncRead(impl func(src string) (test.Cfg, error)) *CfgReaderMock {
	mock.impl.Read = impl
	return mock
}

// SetReturnRead sets a fake method.
func (mock *CfgReaderMock) SetReturnRead(r0 test.Cfg, r1 error) *CfgReaderMock {
	mock.impl.Read = func(string) (test.Cfg, error) {
		return r0, r1
	}
	return mock
}

// fakeZeroRead is a fake method which returns zero values.
func (mock CfgReaderMock) fakeZeroRead(src string) (test.Cfg, error) {
	var (
		r0 test.Cfg
		r1 error
	)
	return r0, r1
}
