package test

// Don't edit this file.
// This file is generated by gomic 0.5.1.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// CmdExecuterMock is a mock.
	CmdExecuterMock struct {
		t                      *testing.T
		name                   string
		callbackNotImplemented gomic.CallbackNotImplemented
		impl                   struct {
			Exec func(cmd, dest string) error
		}
	}
)

// NewCmdExecuterMock returns CmdExecuterMock .
func NewCmdExecuterMock(t *testing.T, cb gomic.CallbackNotImplemented) *CmdExecuterMock {
	return &CmdExecuterMock{t: t, callbackNotImplemented: cb}
}

// Exec is a mock method.
func (mock CmdExecuterMock) Exec(cmd, dest string) error {
	methodName := "Exec" // nolint: goconst
	if mock.impl.Exec != nil {
		return mock.impl.Exec(cmd, dest)
	}
	if mock.callbackNotImplemented != nil {
		mock.callbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroExec(cmd, dest)
}

// SetFuncExec sets a method and returns the mock.
func (mock *CmdExecuterMock) SetFuncExec(impl func(cmd, dest string) error) *CmdExecuterMock {
	mock.impl.Exec = impl
	return mock
}

// SetReturnExec sets a fake method.
func (mock *CmdExecuterMock) SetReturnExec(r0 error) *CmdExecuterMock {
	mock.impl.Exec = func(string, string) error {
		return r0
	}
	return mock
}

// fakeZeroExec is a fake method which returns zero values.
func (mock CmdExecuterMock) fakeZeroExec(cmd, dest string) error {
	var (
		r0 error
	)
	return r0
}
