package test

// Don't edit this file.
// This file is generated by gomic 0.4.0.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// FileReaderMock is a mock.
	FileReaderMock struct {
		t                      *testing.T
		name                   string
		CallbackNotImplemented gomic.CallbackNotImplemented
		Impl                   FileReaderMockImpl
	}

	// FileReaderMockImpl holds functions which implement interface's methods.
	FileReaderMockImpl struct {
		Read func(src string) (string, error)
	}
)

// NewFileReaderMock returns FileReaderMock .
func NewFileReaderMock(t *testing.T, cb gomic.CallbackNotImplemented) *FileReaderMock {
	return &FileReaderMock{t: t, CallbackNotImplemented: cb}
}

// Read is a mock method.
func (mock FileReaderMock) Read(src string) (string, error) {
	methodName := "Read" // nolint: goconst
	if mock.Impl.Read != nil {
		return mock.Impl.Read(src)
	}
	if mock.CallbackNotImplemented != nil {
		mock.CallbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroRead(src)
}

// SetFakeRead sets a fake method.
func (mock *FileReaderMock) SetFakeRead(r0 string, r1 error) {
	mock.Impl.Read = func(src string) (string, error) {
		return r0, r1
	}
}

// fakeZeroRead is a fake method which returns zero values.
func (mock FileReaderMock) fakeZeroRead(src string) (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}
