package test

// Don't edit this file.
// This file is generated by gomic 0.5.2.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	test "github.com/suzuki-shunsuke/go-gencfg/internal/domain"
	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// StrFormatterMock is a mock.
	StrFormatterMock struct {
		t                      *testing.T
		name                   string
		callbackNotImplemented gomic.CallbackNotImplemented
		impl                   struct {
			Format func(dest, text string, formatters []string, reader test.FileReader, executer test.CmdExecuter) (string, error)
		}
	}
)

// NewStrFormatterMock returns StrFormatterMock .
func NewStrFormatterMock(t *testing.T, cb gomic.CallbackNotImplemented) *StrFormatterMock {
	return &StrFormatterMock{
		t: t, name: "StrFormatterMock", callbackNotImplemented: cb}
}

// Format is a mock method.
func (mock StrFormatterMock) Format(dest, text string, formatters []string, reader test.FileReader, executer test.CmdExecuter) (string, error) {
	methodName := "Format" // nolint: goconst
	if mock.impl.Format != nil {
		return mock.impl.Format(dest, text, formatters, reader, executer)
	}
	if mock.callbackNotImplemented != nil {
		mock.callbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroFormat(dest, text, formatters, reader, executer)
}

// SetFuncFormat sets a method and returns the mock.
func (mock *StrFormatterMock) SetFuncFormat(impl func(dest, text string, formatters []string, reader test.FileReader, executer test.CmdExecuter) (string, error)) *StrFormatterMock {
	mock.impl.Format = impl
	return mock
}

// SetReturnFormat sets a fake method.
func (mock *StrFormatterMock) SetReturnFormat(r0 string, r1 error) *StrFormatterMock {
	mock.impl.Format = func(string, string, []string, test.FileReader, test.CmdExecuter) (string, error) {
		return r0, r1
	}
	return mock
}

// fakeZeroFormat is a fake method which returns zero values.
func (mock StrFormatterMock) fakeZeroFormat(dest, text string, formatters []string, reader test.FileReader, executer test.CmdExecuter) (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}
