package test

// Don't edit this file.
// This file is generated by gomic 0.5.1.
// https://github.com/suzuki-shunsuke/gomic

import (
	testing "testing"

	gomic "github.com/suzuki-shunsuke/gomic/gomic"
)

type (
	// TemplateRendererMock is a mock.
	TemplateRendererMock struct {
		t                      *testing.T
		name                   string
		callbackNotImplemented gomic.CallbackNotImplemented
		impl                   struct {
			Render func(txt string, data interface{}) (string, error)
		}
	}
)

// NewTemplateRendererMock returns TemplateRendererMock .
func NewTemplateRendererMock(t *testing.T, cb gomic.CallbackNotImplemented) *TemplateRendererMock {
	return &TemplateRendererMock{t: t, callbackNotImplemented: cb}
}

// Render is a mock method.
func (mock TemplateRendererMock) Render(txt string, data interface{}) (string, error) {
	methodName := "Render" // nolint: goconst
	if mock.impl.Render != nil {
		return mock.impl.Render(txt, data)
	}
	if mock.callbackNotImplemented != nil {
		mock.callbackNotImplemented(mock.t, mock.name, methodName)
	} else {
		gomic.DefaultCallbackNotImplemented(mock.t, mock.name, methodName)
	}
	return mock.fakeZeroRender(txt, data)
}

// SetFuncRender sets a method and returns the mock.
func (mock *TemplateRendererMock) SetFuncRender(impl func(txt string, data interface{}) (string, error)) *TemplateRendererMock {
	mock.impl.Render = impl
	return mock
}

// SetReturnRender sets a fake method.
func (mock *TemplateRendererMock) SetReturnRender(r0 string, r1 error) *TemplateRendererMock {
	mock.impl.Render = func(string, interface{}) (string, error) {
		return r0, r1
	}
	return mock
}

// fakeZeroRender is a fake method which returns zero values.
func (mock TemplateRendererMock) fakeZeroRender(txt string, data interface{}) (string, error) {
	var (
		r0 string
		r1 error
	)
	return r0, r1
}
